#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Motor,  motorB,          LEFT,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RIGHT,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int currentPower = 25, colorReflectiveValue, nTurnRatio = -40;



task readColorReflective(){
	while(true){
		colorReflectiveValue = getColorReflected(colorSensor);
		displayBigTextLine(5,"CR: %i",colorReflectiveValue);
	}// END OF WHILE LOOP
}// END OF readColorReflective()

task controllerTask(){
	while(true){

		// If the current color is <= 10, reverse the direction
		if(colorReflectiveValue <= 10){
			nTurnRatio *= -1;
			repeatUntil(colorReflectiveValue >= 43){

			}
		}
		if(colorReflectiveValue >= 43){
			nTurnRatio *= -1;
			repeatUntil(colorReflectiveValue <= 10){

			}
		}
	}// END OF WHILE LOOP
}// END OF readColorReflective()






task main(){
	startTask(readColorReflective);
	startTask(controllerTask);
	while(true){
		setMotorSync(RIGHT,LEFT,nTurnRatio,currentPower);
	}
}
